sudo: false
language: cpp

git:
  depth: 1

matrix:
  include:
    - env: CXX_COMPILER="g++-5"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5', 'g++-5']
    - env: CXX_COMPILER="clang++"

install:
  - export CXX="${CXX_COMPILER}"
      
script:
  - make

cache:
  - apt: true

notifications:
  email: false
